- job:
    name: oslo.log-src-grenade-devstack
    parent: legacy-dsvm-base
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    post-run: playbooks/legacy/oslo.log-src-grenade-devstack/post.yaml
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/oslo.log
    run: playbooks/legacy/oslo.log-src-grenade-devstack/run.yaml
    timeout: 10800

- project:
    name: openstack/oslo.log
    check:
      jobs:
        - oslo.log-src-grenade-devstack

    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - release-notes-jobs-python3
      - periodic-stable-jobs
